name: fc
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - getopt-win32=0.1
  - graphite2=1.3.14
  - graphviz=14.1.0
  - gts=0.7.6
  - harfbuzz=12.2.0
  - icu=75.1
  - lerc=4.0.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgd=2.3.3
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libzlib=1.3.1
  - openjdk=21.0.9
  - openssl=3.6.0
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - python=3.13.11
  - python-graphviz=0.21
  - python_abi=3.13
  - symlink-exe-runtime=1.0
  - tk=8.6.13
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - zstd=1.5.7
  - pip:
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - asttokens==3.0.1
    - colorama==0.4.6
    - comm==0.2.3
    - contourpy==1.3.3
    - cycler==0.12.1
    - debugpy==1.8.17
    - decorator==5.2.1
    - dgraph_flex==0.1.11
    - executing==2.2.1
    - fastcda==0.1.18
    - fonttools==4.61.0
    - ipykernel==7.1.0
    - ipython==9.8.0
    - ipython_pygments_lexers==1.1.1
    - ipywidgets==8.1.8
    - jedi==0.19.2
    - joblib==1.5.2
    - jpype1==1.6.0
    - jupyter_client==8.6.3
    - jupyter_core==5.9.1
    - jupyterlab_widgets==3.0.16
    - kiwisolver==1.4.9
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mpmath==1.3.0
    - nest-asyncio==1.6.0
    - numdifftools==0.9.41
    - numpy==2.3.5
    - packaging==25.0
    - pandas==2.3.3
    - parso==0.8.5
    - patsy==1.0.2
    - pillow==12.0.0
    - platformdirs==4.5.1
    - prompt_toolkit==3.0.52
    - psutil==7.1.3
    - pure_eval==0.2.3
    - pyaml==25.7.0
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - pyzmq==27.1.0
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - seaborn==0.13.2
    - semopy==2.3.11
    - six==1.17.0
    - stack-data==0.6.3
    - statsmodels==0.14.6
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - tzdata==2025.2
    - wcwidth==0.2.14
    - widgetsnbextension==4.0.15

prefix: "C:\\Users\\VHAMINLimK\\AppData\\Local\\miniforge3\\envs\\fc"
